// Mocks generated by Mockito 5.4.4 from annotations
// in core/test/application/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/src/services/interfaces/i_authentication_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDetailsDTO_0 extends _i1.SmartFake
    implements _i2.UserDetailsDTO {
  _FakeUserDetailsDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthenticationService extends _i1.Mock
    implements _i3.IAuthenticationService {
  MockIAuthenticationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserDetailsDTO> getUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #getUserDetails,
          [],
        ),
        returnValue: _i4.Future<_i2.UserDetailsDTO>.value(_FakeUserDetailsDTO_0(
          this,
          Invocation.method(
            #getUserDetails,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserDetailsDTO>);

  @override
  _i4.Future<_i2.UserDetailsDTO> loginWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.UserDetailsDTO>.value(_FakeUserDetailsDTO_0(
          this,
          Invocation.method(
            #loginWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserDetailsDTO>);

  @override
  _i4.Future<_i2.UserDetailsDTO> signupWithEmailAndPassword({
    required String? email,
    required String? password,
    String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signupWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
          },
        ),
        returnValue: _i4.Future<_i2.UserDetailsDTO>.value(_FakeUserDetailsDTO_0(
          this,
          Invocation.method(
            #signupWithEmailAndPassword,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserDetailsDTO>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
