// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7BBFtjo6hOqIhAuICo-NJSLZeFz-_EjY',
    appId: '1:375024596512:web:80ed49c3d46857fb0eee45',
    messagingSenderId: '375024596512',
    projectId: 'riga-music',
    authDomain: 'riga-music.firebaseapp.com',
    storageBucket: 'riga-music.appspot.com',
    measurementId: 'G-YZ85RWBKLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuioCmrQjtAAeyDn4n2b9_T07ibsFtGw',
    appId: '1:375024596512:android:990b9d8fc555dbc90eee45',
    messagingSenderId: '375024596512',
    projectId: 'riga-music',
    storageBucket: 'riga-music.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsIuQ9vthlcK2-cl1aTe2R4uwXViPaY4',
    appId: '1:375024596512:ios:9bb837a0950db3480eee45',
    messagingSenderId: '375024596512',
    projectId: 'riga-music',
    storageBucket: 'riga-music.appspot.com',
    iosBundleId: 'com.example.rigaMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsIuQ9vthlcK2-cl1aTe2R4uwXViPaY4',
    appId: '1:375024596512:ios:9bb837a0950db3480eee45',
    messagingSenderId: '375024596512',
    projectId: 'riga-music',
    storageBucket: 'riga-music.appspot.com',
    iosBundleId: 'com.example.rigaMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7BBFtjo6hOqIhAuICo-NJSLZeFz-_EjY',
    appId: '1:375024596512:web:7f7af11c9f7b99900eee45',
    messagingSenderId: '375024596512',
    projectId: 'riga-music',
    authDomain: 'riga-music.firebaseapp.com',
    storageBucket: 'riga-music.appspot.com',
    measurementId: 'G-10GKYL4MZL',
  );

}