name: core
description: "riga_music backend"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  models:
    path: ../models
  get_it: ^7.6.4
  injectable: ^2.3.5
  injectable_generator: ^2.4.2
  flutter_bloc: ^8.1.6
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
