// Mocks generated by Mockito 5.4.4 from annotations
// in core/test/application/youtube/youtube_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/src/services/interfaces/i_youtube_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVideosListDTO_0 extends _i1.SmartFake implements _i2.VideosListDTO {
  _FakeVideosListDTO_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IYouTubeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIYouTubeService extends _i1.Mock implements _i3.IYouTubeService {
  MockIYouTubeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VideosListDTO> getVideosList({
    required String? playListId,
    String? pageToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideosList,
          [],
          {
            #playListId: playListId,
            #pageToken: pageToken,
          },
        ),
        returnValue: _i4.Future<_i2.VideosListDTO>.value(_FakeVideosListDTO_0(
          this,
          Invocation.method(
            #getVideosList,
            [],
            {
              #playListId: playListId,
              #pageToken: pageToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.VideosListDTO>);
}
