name: RigaMusic - Android Dev

on: 
  push:
    branches:
      - develop-2
  pull_request:
    branches:
      - develop-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.3
      
      - name: Create .env file
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env

      - name: Install dependencies
        run: |
          flutter pub get
      
      - name: Auto format Dart code
        run: dart format .

      - name: Verify the format of the Dart code
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze the Dart code
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > android/app/google-services.json
      
      - name: Build APK
        run: flutter build apk --debug --build-name=1.0.0 --build-number=1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: upload artifact to Firebase App Distribution
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-debug.apk