name: RigaMusic - iOS Dev

on: 
  push:
    branches:
      - develop-2
  pull_request:
    branches:
      - develop-2

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.24.3

      - name: Create .env file
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
      
      - name: Decode and create GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist
    
      - name: Install dependencies
        run: |
          flutter pub get

      - name: Auto format Dart code
        run: dart format .

      - name: Verify the format of the Dart code
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze the Dart code
        run: flutter analyze --fatal-warnings

      #- name: Run tests
      #  run: flutter test

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app (Debug)
        run: |
            flutter build ios --debug --build-name=1.0.0 --build-number=1 --no-codesign